### ISSUE TITLE
get error could not find widget 'Googlemaps' in the widget directory ??

### ISSUE THREAD

**Issue by florishakvoort** [mendixlabs/google-maps#20] opened 2017-11-02 16:03 UTC

**Comment by mistaguy** [comment] 2017-11-07 13:28
@florishakvoort 
Please provide the version of the google maps widget you are using. as well as the mendix version. 
Steps to reproduce the error will be useful as well.

**Comment by Andries-Smit** [comment] 2018-01-26 08:36
Dear Floris

We will close this issue as there are no details to reproduce the issue. 
A newer version is release since opening the issue
If the issue still persist please provide us with more information. 

Cheers, Andries

**Closed by Andries-Smit** 2018-01-26 08:36 UTC
Labels: invalid
